name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build Bootstrap .tipa
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git remote add upstream https://github.com/RootHide/Bootstrap
          git fetch upstream
          git fetch --all --prune
          git pull --rebase --strategy-option=theirs upstream main

      - name: Debug Output
        run: |
          pwd
          ls -l
    
      - name: Install brew
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"

      - name: Install Theos
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos')"

      - name: Install make
        run: brew install make

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make Bootstrap Package
        run: gmake -j$(sysctl -n hw.ncpu) package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./packages/Bootstrap.tipa

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: Bootstrap.tipa
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Rolling Release
          body: These are automatically updated builds of the latest Bootstrap commit.
          artifacts: "Bootstrap.tipa"
          tag: release
          token: ${{ secrets.GITHUB_TOKEN }}
